scripts/generate_deb.sh.in: find distribution name/version from lsb-release to use in filename.

diff --git a/scripts/generate_deb.sh.in b/scripts/generate_deb.sh.in
--- a/scripts/generate_deb.sh.in
+++ b/scripts/generate_deb.sh.in
@@ -10,12 +10,23 @@ PACKAGE_BINDIR="@CMAKE_INSTALL_BINDIR@"
 PACKAGE_SHAREDIR="@CMAKE_INSTALL_DATADIR@/@CMAKE_PROJECT_NAME@"
 PACKAGE_TMPDIR="tmp/debroot"
 
+if [[ -f /etc/upstream-release/lsb-release ]]; then
+  source /etc/upstream-release/lsb-release
+elif [[ -f /etc/lsb-release ]]; then
+  source /etc/lsb-release
+else
+  echo "ERROR: could not determine debian release."
+  exit 1
+fi
+
+DISTRIB_ID=$(echo $DISTRIB_ID | tr '[:upper:]' '[:lower:]')
+
 # Default to 1 if no release is set.
 if [[ -z $RELEASE ]]; then
   RELEASE="1"
 fi
 
-PACKAGE_FULLNAME="${PACKAGE_NAME}_${PACKAGE_VERSION}-${RELEASE}_amd64"
+PACKAGE_FULLNAME="${PACKAGE_NAME}_${PACKAGE_VERSION}-${RELEASE}-${DISTRIB_ID}-${DISTRIB_RELEASE}_amd64"
 
 rm -fr ${BASE_DIR}/${PACKAGE_TMPDIR}
 
